version: '3.7'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: questiondb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: questionservice@pp123
    ports:
      - "6904:5432"