version: '3.7'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: quizdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: quizservice@pp123
    ports:
      - "6905:5432"